### ISSUE TITLE
Hyperlinks are not shown as links

### ISSUE THREAD

**Issue by antitree** [Interlock-Rochester/interlock-rochester.github.io#10]
Hyperlinks (e.g. contact page) do not appear different from normal text so you don't know that they're links. Add some kind of decorator in the CSS.

**Comment by jnwatts** [comment]
I can fix the problem, but I'd like to know which direction you folks would prefer:
* blue w/ no underline -> hover: blue w/ underline
* blue w/ underline
* black w/ underline
* black w/ underline -> hover: blue w/ underline

Pretty trivial to get to any of the desired states, but it's all a matter of preference.
