### ISSUE TITLE
Implement HTTPS with Cloudflare

### ISSUE THREAD

**Issue by antitree** [Interlock-Rochester/interlock-rochester.github.io#2]
AFAIK, the only way to do HTTPS with a custom domain in github is to use a third party proxy like Cloudflare (I'd love to have an alternative to cloudflare but there it is)

## Directions:
* https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/

## Specific configuration settings:

* Crypto>SSL Full (strict) for HSTS
* Firewall>Set WAF security to "Minimal almost non-existant" (so that tor users aren't always prompted to use a captcha)
* Crypto>TLS 1.3
* Speed>Auto-minify

**Comment by deejoe** [comment]
if ghpt is ok with it we can work on configuring Let's Encrypt for the existing hosting.

**Comment by ghost** [comment]
FWIW, I set up https twice last week with Let's Encrypt, and it was
really quick & easy just following their prompts on the letsencrypt
utility.

(I've forgotten who suggested letsencrypt to me on #interlock,
but thanks.)

**Comment by antitree** [comment]
Done. Cloudflare now fronts the website.
