### ISSUE TITLE
Mobile: Title wraps to a newline creating an unsightly gap on page

### ISSUE THREAD

**Issue by antitree** [Interlock-Rochester/interlock-rochester.github.io#8]
## issue
The mobile CSS isn't designed for a super long title like "Interlock Rochester - Rochester's Hackerspace" because on certain mobile resolutions, it will just wrap causing a large white space at the top. 

## Reproduction steps
Look at the page on mobile or emulate any mobile device (found on a Pixel). Notice that the title "Interlock Rochester - Rochester's Hackerspace" wraps and leaves a big white space in the top left. 

## Potential fixes:
* Modify the CSS to not wrap and just cut it off from the title
* Modify the title to be shorter so that it doesn't wrap
* Shrink the fonts on the mobile view
* Some kind of terrible javascript that rips out the tag line portion when viewed on mobile

**Comment by jnwatts** [comment]
How about some kind of not terrible CSS that rips out the tag line portion? ;-)
